// auth
export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const SET_ENTRY_URL = 'setEntryUrl'
export const REMOVE_ENTRY_URL = 'removeEntryUrl'
export const REMOVE_AUTH = 'removeAuth'

// general
export const SET_PAGE_CLASS = 'setPageClass'
export const SET_META = 'setMeta'

// popups
export const SHOW_POPUP = 'showPopup'
export const SET_POPUP = 'setPopup'
export const SET_PREVENT_SHOW_POPUP = 'setPreventShowPopup'
export const CLOSE_POPUP = 'closePopup'
export const TWO_FACTOR = 'twoFactor'

// wallet
export const SET_CREATE_MNEMONIC = 'setCreateMnemonic'
export const SET_CREATE_ADDRESS = 'setCreateAddress'
export const SET_MNEMONIC = 'setMnemonic'
export const SET_ADDRESS = 'setAddress'
export const SET_HD_PATH = 'setHdPath'
export const SET_ACCOUNT_DATA = 'setAccountData'
export const SET_VALIDATORS = 'setValidators'
export const SET_TOTAL_BONDED = 'setTotalBonded'
export const SET_BALANCE = 'setBalance'
export const SET_BALANCES_UPDATED = 'setBalancesUpdated'
export const SET_LOAD_INTERVAL_ID = 'setLoadIntervalId'
export const RESET_BALANCES = 'resetBalances'
export const SET_DELEGATIONS = 'setDelegations'
export const SET_REWARDS = 'setRewards'
export const SET_UNBONDING = 'setUnbonding'
export const SET_TAB_STATE = 'setTabState'
export const RESET_TAB_STATE = 'resetTabState'
export const RESET_ALL_ACCESS = 'resetAllAccess'
export const SET_COIN_PRICE = 'setCoinPrice'